local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 3.0
      resolution: 0.05
      footprint: "[[0.30, 0.14], [0.30, -0.14], [-0.04, -0.14], [-0.04, 0.14]]"
      plugins: ["obstacle_layer", "inflation_layer"]
      inflation_layer:
        inflation_radius: 0.2

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      resolution: 0.05
      footprint: "[[0.30, 0.14], [0.30, -0.14], [-0.04, -0.14], [-0.04, 0.14]]"
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        map_topic: "/map"
      inflation_layer:
        inflation_radius: 0.2

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    controller_plugins: ["follow_path"]
    follow_path:
      plugin: "dwb_core::DWBLocalPlanner"
      sim_time: 1.2
      vx_samples: 15
      vtheta_samples: 15